nrfconnect/sdk-mcuboot

- Jenkinsfile
Changed of the way that parameters are set for the compliance script. Previously that was failing for branches that would not require additional report parameters to be send for the script. This PR should fix false negative results of the compliance script for master and the branches.
Only pull requests will receive parameters for the comparison of commits. 
Otherwise will compare with the origin.
Signed-off-by: Chris Bittner <chris.bittner@nordicsemi.no>
> [nrf noup] ci: Applied fix for compliance script parameters

- Jenkinsfile
CI failure on any stage of fw-nrfconnect-mcuboot testing
will case email to be send to code owner to identify 
the root cause or the responsible person.
Signed-off-by: Chris Bittner <chris.bittner@nordicsemi.no>
> [nrf noup] ci: CI failure on master or PR will send email to code owner

- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
- zephyr/CMakeLists.txt
- zephyr/Kconfig
dump
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> [nrf fromlist] cmake: kconfig: zephyr multi image built support

- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
- scripts/imgtool/main.py
* do not override TEXT_SECTION_OFFSET (The nrf52840_pca10059 board no longer
overrides TEXT_SECTION_OFFSET but sets the correct FLASH_LOAD_OFFSET
instead)
* Fix bug https://github.com/JuulLabs-OSS/mcuboot/issues/399 where dts.overlay was not being appended.
* imgtool disallow using public RSA key for signing.
> DNM [nrf mergeup] merge upstream up to commit 288682c

- boot/zephyr/CMakeLists.txt
Currently the BOARD variable is not checked before setting the
default value. This causes issues in a multi image context.
Fix this by checking if the BOARD variable is set before
setting it to its default value.
> cmake: check BOARD before setting default

- zephyr/CMakeLists.txt
This reduces the lengths of the filepath created for the build directory
so that it won't exceed 259 characters on windows. This also aligns with
the changes introduced with https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/647
Signed-off-by: Sigvart Hovland <sigvart.m@gmail.com>
> zephyr: cmake: Fix for too long file paths in zephyr

- zephyr/CMakeLists.txt
Prior to this, the update hex was deduced from the update.bin.
The problem is that update.bin does not have the end padding.
The end padding is required for mcuboot to upgrade a hex file
flashed directly to the secondary slot.
Fix this by having a separate sign command for update.hex which
includes the --pad argument. This enables the user to verify
the update process by flashing the update.hex file directly to
the board.
> zephyr: cmake: build update hex with --pad

- boot/zephyr/CMakeLists.txt
Fix the TINYCBOR build scripts to work with multi-image.
This patch comes from https://github.com/JuulLabs-OSS/mcuboot/pull/430/files
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> [nrf fromlist] cmake: Fix TINYCBOR in a multi-image context

- boot/zephyr/Kconfig
Add button 1 as default serial detect pin for nrf9160_pca10090
Signed-off-by: Andreas Vibeto <andreas.vibeto@nordicsemi.no>
> [nrf fromlist] boot: serial recovery: Add pca10090 default detect pin

- zephyr/CMakeLists.txt
Upstream changed the name of 'kernel_elf' to 'zephyr_final', in this
commit we do the same renaming.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> [nrf toup] cmake: Align with renaming kernel_elf to zephyr_final

- boot/zephyr/serial_adapter.c
Follow the device name changes in Zephyr.
Signed-off-by: Filip Kubicz <filip.kubicz@nordicsemi.no>
> [nrf toup] boot: zephyr: Update USB CDC ACM device name

- boot/zephyr/CMakeLists.txt
- zephyr/CMakeLists.txt
Use the automatically generated hex file for the app partition.
Depends on: https://github.com/NordicPlayground/fw-nrfconnect-zephyr/pull/146 and https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/768
> zephyr: cmake: Adapt to new hex file handling in Partition Manager

- zephyr/CMakeLists.txt
When a parent image selects MCUboot, it should be signed regardless
of whether or not mcuboot is being built from source.
> [nrf toup] cmake: sign parent image regardless of build strategy

- zephyr/CMakeLists.txt
- zephyr/Kconfig
Make it easier for the user to change the mcuboot version
by extracting this as a kconfig variabl.
> kconfig: add config for mcuboot version

- zephyr/CMakeLists.txt
It is required to depend on both the wrapper target and the file.
This patch adds the missing file dependency.
Prior to this signed.hex (and following files) were not updated
upon code change.
> cmake: fix dependency for merged files to sign

- zephyr/CMakeLists.txt
This is needed when the properties are automatically set.
> zephyr: cmake: Use PM properties with the proper names

- Jenkinsfile
Managing Docker version, Agent Labels, Github Status, manifest updates, downstream jobs from CI_LIB.
More info: https://projecttools.nordicsemi.no/confluence/display/NCS/Linking+Jenkins+Jobs+Together
Signed-off-by: Thomas Stilwell Thomas.Stilwell@nordicsemi.no
> [nrf noup] ci: use Standard Library in Jenkinsfile to link sub-projects together

- boot/zephyr/CMakeLists.txt
Contained in upstream pr https://github.com/JuulLabs-OSS/mcuboot/pull/430
This variable is per image, treat it is such.
> [nrf fromlist] cmake: image-ify DTC_OVERLAY_FILE

- zephyr/CMakeLists.txt
This is needed for serial recovery to work using hex files.
Prior to this the update.hex got TLV data at the end of the
partition, which caused many blank pages to be included,
which made it hard to use in a serial recovery scheme.
Instead, make update.hex without TLV data at the end,
and provide a new file test_update.hex which contains
the TLV data, and can be directly flashed to test the
upgrade procedure.
> [nrf toup] cmake: make update.hex without trailer data

- boot/zephyr/Kconfig
- zephyr/Kconfig
Leverage the kconfig template functionality to have cleaner
Kconfig code which is also less error prone.
> kconfig: use template for partition manager config

- Jenkinsfile
- docs/Gemfile.lock
This CI plan will skip Linting if '[nrf mergeup]' is in the title. 
Also cherry-picked CVE from upstream which seemed urgent.
> [nrf temphack] ci: Skip GitLint compliance check if PR-title has [nrf mergeup]

- zephyr/CMakeLists.txt
Sign both S0 and S1 (which is already signed by B0) in order to prepare update candidates for both slots.
> Create update candidate for S1 and S0

- boot/zephyr/pm.yml
All partitions used by mcuboot must be page size aligned.
Leverage newly added alignment feature to enforce this.
> [nrf toup] partition_manager: add partition alignment

- zephyr/CMakeLists.txt
Previously this injection took place earlier in the build process,
resulting in menuconfig data being overwritten.
By moving the injection here, the menuconfig data is not
overwritten.
> [nrf noup] cmake: inject kconfig from mcuboot cmakelist

- boot/zephyr/Kconfig
- boot/zephyr/serial_adapter.c
zephyr changes the way in which it provide name of
serial device used by serial recover.
see: zephyrproject-rtos/zephyr#18752
This path introduce build time configuration of device name
which is set to exact the same device which was set before.
> [nrf fromlist]zephyr/serial_recovery: fix serial device binding

- boot/bootutil/include/bootutil/sha256.h
- boot/zephyr/Kconfig
- ext/nrf/cc310_glue.h
Fix some dependencies issues with the Kconfig for shared crypto and add
a check in the `sha256` API to allow for `NRF_EXTERNAL_CRYPTO`. Set
`NRF_CRYPTOCELL` to `NRF_CRYPTOCELL_S` since MCUBoot is typically
running in secure-zone.
Fixes NCSDK-3413
> bootutil: nrf_cc310: Bugfix for CC310 and shared crypto APIs

- boot/bootutil/include/bootutil/sha256.h
- boot/zephyr/Kconfig
- ext/nrf/cc310_glue.h
Autoamtic backport failed due to access error. Followed the steps proposed by github, and ended up with this PR.
Fix some dependencies issues with the Kconfig for shared crypto and add
a check in the `sha256` API to allow for `NRF_EXTERNAL_CRYPTO`. Set
`NRF_CRYPTOCELL` to `NRF_CRYPTOCELL_S` since MCUBoot is typically
running in secure-zone.
Fixes NCSDK-3413
> [nrf noup] bootutil: nrf_cc310: Bugfix for CC310 and shared crypto API

- zephyr/CMakeLists.txt
- zephyr/Kconfig
It is no longer possible to directly evaluete DT_ within CMakeList,
instead intermediate variable defined within Kconfig needs to be
used.
> [DNM] [nrf noup] Remove direct DT_ constants evaluation in CMakeList

- boot/zephyr/pm.yml
This partition is not used by mcuboot, remove it.
> pm: remove unused partition

- boot/zephyr/main.c
- boot/zephyr/pm.yml
- boot/zephyr/prj.conf
This to enable the secure boot property of the system.
> [nrf noup] lock mcuboot using fprotect before jumping

- boot/zephyr/main.c
- boot/zephyr/prj.conf
If EXT_API_PROVIDE EXT_API is enabled. This is relevant only when
the immutable bootloader has booted mcuboot.
nrf PR: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1886
> [nrf noup] boot: zephyr: Call fw_info_ext_api_provide() before booting

- boot/zephyr/main.c
- boot/zephyr/prj.conf
Fixup for commit
"[nrf noup] boot: zephyr: Call fw_info_ext_api_provide() before booting"
Because of changes in nrf repo (optional EXT_APIs).
> [nrf noup] boot: zephyr: Fixup on fw_info_ext_api_provide()

- boot/zephyr/pm.yml
The `CONFIG_FPROTECT_BLOCK_SIZE` symbol is not resolved when fprotect is
disabled making partition manager fail when trying to compile samples
which disables fprotect in MCUBoot.
> boot: zephyr: Fix pm.yml for devices which are not using fprotect

- boot/zephyr/Kconfig
MCUBoot storage partition was removed a while ago.
This patch removes its orphaned size configuration entry.
> [nrf noup] Kconfig: remove mcuboot_storage size entry

- boot/boot_serial/src/serial_recovery.cddl
- boot/boot_serial/src/serial_recovery_cbor.c
- boot/boot_serial/src/serial_recovery_cbor.h
Was 3, but mcumgr sometimes sends 2 ("off" + "data", "len" is not needed
when "off" != 0). Reduce to 1 to avoid the problem, since the code
has other checks to catch this.
Ref: DESK-939
> [nrf fromtree] serial_recovery: Reduce minimum number of members in packet

- boot/zephyr/main.c
Locking is performed too early, breaking bootloader updates.
Move locking to after validation and swapping.
NCSDK-5330
> [nrf noup] zephyr: move fprotect to where it should be

- boot/bootutil/src/loader.c
- boot/zephyr/CMakeLists.txt
[nrf fromlist] cmake: use find_package to locate Zephyr
Using find_package to locate Zephyr.
Old behavior was to use $ENV{ZEPHYR_BASE} for inclusion of boiler plate
code.
Whenever an automatic run of CMake happend by the build system / IDE
then it was required that ZEPHYR_BASE was defined.
Using ZEPHYR_BASE only to locate the Zephyr package allows CMake to
cache the base variable and thus allowing subsequent invocation even
if ZEPHYR_BASE is not set in the environment.
It also removes the risk of strange build results if a user switchs
between different Zephyr based project folders and forgetting to reset
ZEPHYR_BASE before running ninja / make.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
> [nrf fromlist] cmake: use find_package to locate Zephyr

- boot/zephyr/Kconfig
This fixes issue where mcumgr upload command would result in
device being deleted, but no new image being uploadet
due to timeout while waiting for erase operation.
Ref: NCSDK-5603
> [nrf toup] zephyr: enable progressive erase on nrf53

- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
- boot/zephyr/include/nrf_cleanup.h
- boot/zephyr/main.c
- boot/zephyr/nrf_cleanup.c
Do some cleanup on NRF peripheral.
supersedes #88
> [nrf temphack] clean peripherals state before call the application

- boot/zephyr/include/sysflash/sysflash.h
The FLASH_AREA_IMAGE_SCRATCH redefinition has been introduced with
commit:
97c92cd707fffa1bd35c98e820826aaff347e9a5
> [nrf noup] zephyr: Fix redefinition compiler warning

- boot/zephyr/pm.yml
When single image DFU is used scratch is not needed.
Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>
> boot: zephyr: Use correct pm template

- boot/zephyr/main.c
If software IRQ relay is enabled and VTOR is available,
the bootloader will switch from its real vector table
to the relay vector table before chain-loading to the
application.
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>
Signed-off-by: Krzysztof Taborowski <krzysztof.taborowski@nordicsemi.no>
> [nrf fromtree] boot/zephyr: set VTOR to relay vector before chain-load

- boot/zephyr/CMakeLists.txt
Change fixes build issue that occurs if CONF_FILE is a list of file paths instead of single file path.
> [nrf toup] boot: zephyr: Fix build issue for multiple conf files

- boot/bootutil/src/loader.c
- boot/zephyr/main.c
Enables network core updates of nrf53 using MCUBoot by identifying
images through their start addresses. Also implements the control and
transfer using the PCD module.
Pulled in by https://github.com/nrfconnect/sdk-nrf/pull/2783
> boot: zephyr: nrf53 network core bootloader implementation

- boot/zephyr/Kconfig
- zephyr/Kconfig
SINGLE_IMAGE_DFU option is already defined in boot/zephyr/Kconfig.
Kconfig: move BOOT_SIGNATURE_KEY_FILE to its upstream location
> zephyr/Kconfig: remove SINGLE_IMAGE_DFU duplication

- boot/zephyr/nrf_cleanup.c
To allow compilation on nRF51 which doesn't have any NRF_UARTE.
Related to 664b8ad8b05e9fac567eafcf9fe617303fb6aed6
> [nrf temphack] nrf_cleanup:  Guard includes behind #if defined()

- boot/bootutil/src/loader.c
- boot/bootutil/src/swap_move.c
* fix swap-move brick with padded image0
When the image in the primary slot is padded, the boot source is
considered the primary slot; this results in skipping the typical
initialization of the trailer, which ends up bricking the device. As
it is fine to always initialize the trailer in the primary slot when
starting a new upgrade the extra check was removed.
* fix boostrapping in swap-move
Fix boostrapping in swap-move that was being skipped due to the having
an erased header in the primary slot which caused an early return
because of the requirement of having to re-read image headers when
"moving" an image during an upgrade.
* copy image size with fast overwrite 
Previously when `MCUBOOT_OVERWRITE_ONLY_FAST` was set, the whole amount
of sectors that stored an image were being copied. …
> [nrf fromtree] fixed: swap-move, bootstrapping and fast overwrite mode

- boot/zephyr/Kconfig
Serial recovery protocol doesn't care about writing data in block
of multiples flash write-block-sizes. Therefore the last payload block
which might be not aligned which imposes the flash write alignment error.
This patch select 8-bits access emulation which solves the issue.
Fixes NCSDK-6751
> [nrf temphack] Kconfig: select 8-bits flash access for recovery mode

- boot/zephyr/pm.yml
This commit sets size of second image partition to zero if CONFIG_SINGLE_APPLICATION_SLOT=y, hence the secondary image partition is dropped by partition manager. This allows to use available flash to have bigger slot image without unnecessary workarounds.
Tested with Zigbee samples, mcuboot main() extended to print size and offset of the slot_0 after startup:
`printk("image_0 offset: 0x%x\n", FLASH_AREA_OFFSET(image_0));`
`printk("image_0 size:   0x%x\n", FLASH_AREA_SIZE(image_0));`
Zigbee sample built with:
`west build -b nrf52840dk_nrf52840 --pristine -s ~/GIT/ncs/nrf/samples/zigbee/light_switch -- -Dmcuboot_OVERLAY_CONFIG="usb_cdc_acm_log_recovery.conf single_slot.conf" -DCONFIG_BOOTLOADER_MCUBOOT=y -DPM_STATIC_YML_FILE=/home/sedr/GIT/ncs/nrf/samples/zigbee/ncp/configuration/nrf52840dk_ …
> mcuboot: Don't create second image partition in single slot build

- boot/zephyr/pm.yml
Scratch area was declared for BOOT_UPGRADE_ONLY unnecessarily.
> [nrf noup] pm: BOOT_UPGRADE_ONLY doesn't need scratch area

- boot/bootutil/src/loader.c
Seems multi-image dependencies are not supported for multi-image in NCS
yet. This is a hack which reverts it to how it worked previously in
MCUboot. So that Immutable bootloader + MCUBoot type of builds will work
again.
Ref. NCSDK-8681
> [nrf temphack] bootutil: loader: Fix multi-image variant builds

- boot/bootutil/include/bootutil/crypto/ecdsa_p256.h
-When mcuboot was used with external crypto for firmware
validation it fails to remove the compression byte from
the key so it fails the validation. This removes the
byte as needed.
sdk-nrf PR: [pull/4700](https://github.com/nrfconnect/sdk-nrf/pull/4700)
Downstream commit with function addition: [48aee5f6](https://github.com/nrfconnect/sdk-mcuboot/commit/48aee5f6)
Ref: NCSDK-9848
Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>
> Fix signature validation on external crypto

- boot/bootutil/zephyr/CMakeLists.txt
Fix for max path length on Windows OS.
Switch to use zephyr_library_named() which creates a shorter library name.
[KRKNWK-10479]  - Unable to build on Windows - path length limit
Signed-off-by: Mariusz Poslinski <mariusz.poslinski@nordicsemi.no>
> [nrf fromtree] cmake: fix for max path length on Windows OS

- boot/bootutil/src/loader.c
- boot/zephyr/main.c
Only include pcd.h in mcuboot when CONFIG_NRF53_UPGRADE_NETWORK_CORE is defined
ref: NCSDK-7433
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>
> [nrf noup] mcuboot: Only include pcd.h if the nRF53 network core is being upgraded

- boot/bootutil/include/bootutil/bootutil_public.h
- boot/bootutil/src/bootutil_public.c
- boot/bootutil/src/loader.c
Parent PR: https://github.com/mcu-tools/mcuboot/pull/1038
In case secondary image device has a malfunction,
It might be still possible to boot the primary image.
This make sense especially if the secondary image resides in an
external flash which might be damaged while SoC is still working.
> [nrf fromtree] Allow to boot primary image if secondary one is unreachable

- boot/bootutil/src/loader.c
- boot/zephyr/main.c
this is amendment to
https://github.com/nrfconnect/sdk-mcuboot/commit/d362b129cb18
fixes>
[57/300] Building C object CMakeFiles/app.dir/main.c.obj
/home/ludu/git/nrfconnect_chip/bootloader/mcuboot/boot/zephyr/main.c: In function 'main':
/home/ludu/git/nrfconnect_chip/bootloader/mcuboot/boot/zephyr/main.c:584:5: warning: implicit declaration of function 'pcd_lock_ram' [-Wimplicit-function-declaration]
584 |     pcd_lock_ram();
|     ^~~~~~~~~~~~
[96/300] Building C object CMakeFiles/app.dir/home/ludu/git/nrfconnect_chip/bootloader/mcuboot/boot/bootutil/src/loader.c.obj
/home/ludu/git/nrfconnect_chip/bootloader/mcuboot/boot/bootutil/src/loader.c: In function 'boot_validated_swap_type': …
> [nrf noup] boot: limited pcd routines calls to network core update

- boot/zephyr/include/sysflash/sysflash.h
- boot/zephyr/pm.yml
Improve the user experience by leveraging a new kconfig option
which indicates that the MCUboot secondary slot should be stored
in external flash region.
Ref: NCSDK-10375
> [nrf noup] partition_manager: improve support for external flash 

- boot/zephyr/include/sysflash/sysflash.h
instead of checking if CONFIG_SECURE_BOOT is set. This because
CONFIG_SECURE_BOOT is only set for the parent image.
Ref: NCSDK-10375
> [nrf noup] sysflash: check if B0 address is present

- boot/zephyr/pm.yml
Leverage recently added support for sharing size across regions
in partition manager. This way it is no longer required to
manually specify the size of the MCUboot secondary partition
when it is stored in external flash.
Ref: NCSDK-10375
> [nrf noup] zephyr: pm: share size with primary in all cases

- boot/boot_serial/src/boot_serial.c
- boot/zephyr/Kconfig
Source the file 'Kconfig.mcuboot' from sdk-nrf to reduce the amount
of downstream patches in boot/zephyr/Kconfig.
Ref: NCSDK-11177
> [nrf noup] kconfig: reduce downstream patch

- boot/zephyr/pm.yml
Will be squashed
Change slot alignment to avoid problems in some cases
We cannot align on both end and start, so to ensure that the start
of primary, start of secondary and end of secondary are all aligned, we now use the
new 'align_next' partition manager directive.
> fixup! [nrf noup] treewide: add NCS partition manager support

- boot/zephyr/nrf_cleanup.c
Disable all ppi/dppi channels in case it were used.
fix for NCSDK-12718
> [nrf noup] zephyr/nrf_cleanup: clean-up PPI/DPPI

- boot/zephyr/main.c
The nRF53 mcu has moved RESETREAS register
(from POWER to RESET peripheral).
This fix uses nrfx helper to select the proper register.
Signed-off-by: Radoslaw Koppel <radoslaw.koppel@nordicsemi.no>
> [nrf fromlist] zephyr: Fix serial recovery skipping on nrf53

- boot/zephyr/include/mcuboot-mbedtls-cfg.h
-This enables the MBEDTLS_PLATFORM_ZEROIZE_ALT
definition on Mbed TLS build of the MCUBOOT when
the platform library is enabled. If not defined
the Mbed TLS will compile the zeroize function
and it will cause multiple definition errors.
This is a noup because the configuration
does not exist outside the sdk-nrf.
Ref: NCSDK-13503
Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>
> [nrf noup] boot: zephyr: Enable zeroize ALT func

- boot/bootutil/src/loader.c
The primary slot for the network core is emulated in RAM.
Its flash_area hasn't got relevant boundaries.
Therefore need to override its boundaries for the check.
ref. NCSDK-13532
> [nrf noup] fixed check of reset addres for the net app

- boot/bootutil/src/loader.c
Adds check for network core addresses when NSIB(Nordic Secure Immutable Bootlaoder) is enabled, so that network core updates still will work.
Ref. NCSIDB-696
> [nrf noup] bootutil: loader: Add check for netcore addr if NSIB enabled

- boot/bootutil/src/loader.c
When mcuboot_secondary is on external flash, the image header cannot
dircetly be accessed via secondary_fa->fa_off. Instead the provided
function boot_img_hdr() is used now.
Additionally a similar issue is present when trying to read the address
of the reset handler. For this flash_area_read() is used now.
With this patch is possible to have the update partiton
mcuboot_secondary on external flash and update a updatable
bootloader (mcuboot) in s0 and/or s1.
Signed-off-by: Christian Taedcke <christian.taedcke@lemonbeat.com>
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>
> [nrf noup] loader: Fix reading reset addr to support ext flash

- boot/bootutil/src/loader.c
This reverts commit b0be469b30181e5ddc70a84168f7d95b0337a3df.
> Revert "[nrf noup] loader: Fix reading reset addr to support ext flash"

- boot/zephyr/pm.yml
This patch makes mcuboot_primary_1 ram-flash partition
selectable using CONFIG_NRF53_MCUBOOT_PRIMARY_1_RAM_FLASH
property. This is needed since CONFIG_NRF53_MULTI_IMAGE_UPDATE
become not only configuration which requires that partition.
ref. NCSDK-15698
> pm: enable ram flash partition using common flag

- boot/boot_serial/src/boot_serial.c
- boot/zephyr/Kconfig.serial_recovery
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
Fixes a bug when writing to devices which have memory alignment requirements with data being using directly from a zcbor-response whereby the alignment of the buffer data does not meet the requirements of the flash driver.
Upstream PR: https://github.com/mcu-tools/mcuboot/pull/1533
> [nrf fromlist] boot_serial: Add unaligned stack buffer writing

- boot/bootutil/src/loader.c
This adds the code and logic to support hardware
counters for rollback protection in MCUBOOT
(CONFIG_MCUBOOT_HW_DOWNGRADE_PREVENTION).
Ref: NCSDK-9045
Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>
> [nrf noup] Skip updating sec counters

- boot/zephyr/boards/nrf5340dk_nrf5340_cpuapp_minimal.conf
- boot/zephyr/external_crypto.conf
- boot/zephyr/include/nrf_cleanup.h
- boot/zephyr/nrf_cleanup.c
- boot/zephyr/prj_minimal.conf
NCS has switch to the new license ID some time ago from LicenseRef-BSD-5-Clause-Nordic to new (more
accurate) LicenseRef-Nordic-5-Clause. All source files must be adjusted to the new name.
Ref: NCSIDB-717
> [nrf noup] treewide: Fix old Nordic license ID

- boot/zephyr/boot_serial_extensions.c
... extensions
Moved group definitions to extension source code.
Upstream PR: https://github.com/mcu-tools/mcuboot/pull/1551
> [nrf fromlist] zephyr: Missing header and definitions in boot_serial

- boot/zephyr/main.c
Only call sys_clock_disable when the system clock driver support this feature.
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
(cherry picked from commit 90b8f69040e604254daa7ffe58dd9add985b468a)
Bringing the commit will not hurt us and will allow auto-upmerge to got through, as it currently fails when not finding ` sys_clock_disable `
> [nrf fromtree] boot: zephyr: Only call sys_clock_disable when supported

- boot/zephyr/CMakeLists.txt
- boot/zephyr/include/nrf_cleanup.h
- boot/zephyr/main.c
- boot/zephyr/nrf_cleanup.c
To ensure that MCUBoot does not leak keys or other material through memory to non-secure side we clear the memory before jumping to the next image.
Ref: SI-227
> [nrf noup] zephyr: Clean up non-secure RAM if enabled

- boot/zephyr/Kconfig
This changes the default mcuboot configuration for zephyr applications to clean up before booting the user application. The reason for this change is that mcuboot may configure protection (e.g. MPU stack guard) which is then used by the user application during its startup code prior to cleaning the configuration up, this can lead to a unbootable application and potentially irrecoverable module, therefore cleaning up is now being enabled by default.
Upstream PR: https://github.com/mcu-tools/mcuboot/pull/1635
> [nrf fromlist] boot: zephyr: Clean up before chainloading by default

- boot/bootutil/src/image_ec256.c
The commit 5047f03 breaks the FIH with EC256. This brings the fix from upstream.
> [nrf fromtree] bootutil: Fix FIH return type for EC256

- boot/bootutil/src/loader.c
Memset could have been out optimized by compiler and also not called in error path.
(cherry picked from commit 256bc37aad8f44b9971772a8e48bebf046e47e56)
> [nrf fromtree] bootutil: Fixing memset not beeing called

- boot/zephyr/nrf_cleanup.c
The file nrf_cleanup.c has
#if defined(USE_PARTITION_MANAGER)
Which is true even if USE_PARTITION_MANAGER=n.
This must be changed to "#if USE_PARTITION_MANAGER" for correct behaviour.
Ref: NCSIDB-987
> [nrf noup] bootloader: mcuboot: Fix wrong use of if defined

- boot/bootutil/src/loader.c
- boot/zephyr/include/sysflash/sysflash.h
This adds support for using both NSIB and the multi-image configuration
in MCUboot. Before, this was not possible due to the upgradable bootloader
support through NSIB was using the `UPDATEABLE_IMAGE_NUMBER`
configuration to update the updateable bootloader.
In this commit, we change from using `FLASH_AREA_IMAGE_PRIMARY` to get
the flash area ID to using the bootloader state where we set the flash
area ID of the free updatable bootloader slot if the image is intended
for this slot.
Ref. NCSDK-19223
> [nrf noup] booutil: loader: Add support for NSIB and multi-image

- boot/bootutil/src/loader.c
- boot/zephyr/main.c
Fixes a missing PCD define check, an image might have the network core partition layout set but if PCD support is not enabled then it should not assume that PCD support is part of mcuboot.
> [nrf noup] bootutil: Fix missing PCD define check

- boot/zephyr/include/sysflash/pm_sysflash.h
- boot/zephyr/include/sysflash/sysflash.h
Making sysflash.h and pm_sysflash.h more readable.
**Update 2023-08-11 15:53 UTC**
Fixed copyrights.
**Update 2023-08-16 12:14 UTC**
Rebase from ncs/main
> [nrf noup] Move partition manager definitions to pm_sysflash.h

- boot/bootutil/src/loader.c
Commit 8fe7070ee192f8e72a9a67560cee9e3518155579 broke bootloader updates for nRF91 and non-multi image builds. This commit is fixing this by restoring the previous functionality and `ifdef` out the new logic needed for multi-image.
Ref. NCSDK-23305
> [nrf noup] booutil: loader: Fixup for NSIB and multi-image

- boot/zephyr/flash_map_extended.c
The commit adds missing support for direct upload of third image slots.
(cherry picked from commit 0035c33b447c77233895ae0a8f0d93b83be78ac1)
> [nrf fromtree] zephyr: Provide third image cases for direct image upload

- .github/workflows/commit-tags.yml
Use the generic commit-tags action to provide sauce tag checks.
> [nrf noup] github: Add a commit tags check workflow

- boot/zephyr/CMakeLists.txt
Puts the flash simulation configurtion into cache variables that can be used by other applications and CMake code to know specifics on the simulated flash details
> [nrf noup] zephyr: Add RAM flash configuration to cache for sysbuild

- boot/zephyr/include/sysflash/pm_sysflash.h
A mismatch in defines was made for `_image_1_primary_slot_id` resulting in some configurations not working. This fixes that the linker variable is exposed for mcuboot so that it knows which slot is running an which slot a bootloader upgrade is to be put into.
Ref. NCSDK-19223
> sysflash: pm_sysflash: Fix incorrect include of NSIB image define

- boot/zephyr/main.c
This removes the `return;` to ensure that the application is booted even if EXT_ABI is not provided to the application because it does not include `FW_INFO`.
Added a bit more description to the error messages when FW_INFO is not found and EXT_ABI is not able to be provided to the next image.
Ref. NCSDK-24132
> [nrf noup] boot: zephyr: Boot even if EXT_ABI is not provided

- boot/bootutil/src/loader.c
For nRF53, the only existing version number metadata is stored in the `firmware_info` structure in the network core. This utilizes PCD to read out the version number and compares it against the version number found in the secondary slot for the network core.
Ref. NCSDK-21379
> loader: Add firmware info version check to downgrade prevention

- boot/zephyr/include/mcuboot-mbedtls-cfg.h
The mbedtls platform zeorize function is not provided by the CryptoCell anymore so it is not needed.
This reverts commit 4c1d75f4ac410eb1c365db873bb4be41cc9329c5.
> Revert "[nrf noup] boot: zephyr: Enable zeroize ALT func"

- boot/bootutil/src/loader.c
…dary slot
Added procedure which clean-up content of all the secondary slot which contains valid header but couldn't be assigned to any of supported primary images.
This behavior is needed when configuration allows to use one secondary slot for collecting image for multiple primary slots.
ref.: NCSIDB-1151
> [nrf noup] boot/bootutil/loader: introduced cleanup of unusable secondary slot

- boot/bootutil/src/loader.c
Move ifdefs just to not add code for cleanup unusable slot when direct xip mode is enabled to avoid warnings.
> [nrf noup] loader: remove cleanup for direct xip mode

- boot/zephyr/boards/nrf54l15pdk_nrf54l15_cpuapp_ext_flash.overlay
Align to changes in DTS:
renamed: rram0 -> cpuapp_rram
sized up cpauapp_rram region szie as part of it was reserwed for cpuflpr_rram (which is not used by this config).
> [nrf noup] zephyr/boards: fix nrf54l15pdk ext flash dts overlay

- boot/bootutil/src/loader.c
Fixes an issues with wrongly checking the network core reset address
> [nrf noup] bootutil: loader: Fix netcore address checking

- boot/boot_serial/src/boot_serial_encryption.c
- boot/bootutil/include/bootutil/crypto/aes_ctr.h
- boot/bootutil/include/bootutil/crypto/common.h
- boot/bootutil/include/bootutil/crypto/ecdsa.h
- boot/bootutil/include/bootutil/enc_key.h
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/ed25519_psa.c
- boot/bootutil/src/encrypted.c
- boot/bootutil/src/encrypted_psa.c
- boot/bootutil/src/image_ed25519.c
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/bootutil/src/swap_move.c
- boot/bootutil/zephyr/CMakeLists.txt
- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
- boot/zephyr/include/mcuboot-mbedtls-cfg.h
The PSA encryption is quite complete.
The mbedTLS configuration is rather dodgy.
There are few requirements from upstream and mcuboot upmerge would be nice.
The TODO for reviewers:
- check licenses on [noups]
> PSA implementation of ed25519 image verification and x25519 random key encryption/decryption

- boot/zephyr/Kconfig
- scripts/imgtool/image.py
- scripts/imgtool/main.py
Adds LZMA2 compression to imgtool.
Python lzma library is unable to compress with proper parameters while using "ALONE" container, therefore 2 header bytes are calculated and added to payload by imgtool.
Upstream PR: https://github.com/mcu-tools/mcuboot/pull/2038
> [nrf fromlist] scripts: imgtool: compression

- scripts/imgtool/main.py
fixing broken encryption caused by shift in function parameters.
Upstream PR: https://github.com/mcu-tools/mcuboot/pull/2098
> [nrf fromlist] scipts: imgtool: bugfix #2096

- scripts/imgtool/image.py
- scripts/imgtool/main.py
Adds PureEdDSA signature support.
The change includes implementation of SIG_PURE TLV that, when present, indicates the signature that is present is Pure type.
Upstream PR: https://github.com/mcu-tools/mcuboot/pull/2063
~~Rebased on top of: https://github.com/nrfconnect/sdk-mcuboot/pull/344~~
> [nrf fromlist] imgtool: Add pure signature support

- boot/zephyr/main.c
Previously PCD memory was locked as read-only, non-secure in MCUboot. Given that TF-M also needs write to PCD to communicate with b0n, the memory is left unlocked and locked to read-only, non-secure in TF-M.
> [nrf noup] boot: zephyr: Do not lock PCD region with TF-M

- boot/bootutil/include/bootutil/image.h
- scripts/imgtool/image.py
There was one cherry-pick missing.
> Bring in missing SIG_PURE definition to imgtool.py.

- boot/bootutil/src/ed25519_psa.c
- boot/bootutil/src/image_ed25519.c
- boot/bootutil/src/image_validate.c
- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
KMU support, where image signature is verified using KMU provisioned keys.
To test:
In order to make building possible: Need to include https://github.com/nrfconnect/sdk-mcuboot/pull/352 :
``` diff
--- a/boot/zephyr/prj.conf
+++ b/boot/zephyr/prj.conf
@@ -1,7 +1,6 @@
CONFIG_PM=n
CONFIG_MAIN_STACK_SIZE=10240
-CONFIG_MBEDTLS_CFG_FILE="mcuboot-mbedtls-cfg.h"
CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_ENCRYPT_IMAGE=n
```
``` console
west build  -p -d builds/hello_54_sb_ed_psa_kmu2 -b nrf54l15dk/nrf54l15/cpuapp zephyr/samples/hello_world/ -DSB_CONFIG_BOOTLOADER_MCUBOOT=y -DSB_CONFIG_BOOT_SIGNATURE_TYPE_ED25519=y -Dmcuboot_CONFIG_NRF_SECURITY=y -Dmcuboot_CONFIG_MBEDTLS=n -Dmcuboot_CONFIG_BOOT_ED25519_PSA=y -Dmcuboot_CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x10000 …
```
> ED25519 KMU

- boot/zephyr/decompression.c
fixup! [nrf noup] zephyr: Add support for ARM thumb filter
Fixes some issues with the ARM filter implementation which has been updated to support jump instructions that are staggered into 2 different data chunks, and whereby the final portion of data was not ran through the filter
> [nrf noup] boot: zephyr: decompression: Fix issues with ARM thumb filter

- boot/zephyr/Kconfig
fixup! [nrf noup] zephyr: Add support for compressed image updates
Fixes an issue with a mismatch of the chunk size used when decompressing firmware updates
> [nrf noup] zephyr: Fix compressed chunk size mismatch

- boot/bootutil/src/encrypted_psa.c
- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
Fixes in Kconfig, CMake and on in encryption source where one line got lost, somehow, when moving encryption to separate file.
X25519/AES encryption on nrf54l15 PSA has been retested on target and works fine.
> Set of PSA encryption fixes

- boot/zephyr/decompression.c
fixup! [nrf noup] zephyr: Add support for ARM thumb filter
Fixes two issues with decompression, one with variables not being declared at the correct level and the other with the test decompression not checking the final decompressed image size
> [nrf noup] zephyr: Fix issues with ARM thumb decompression

- boot/zephyr/decompression.c
fixup! [nrf noup] zephyr: Add support for compressed image updates
Fixes an issue when using ECDSA-P256 signing whereby the signature output size is not a fixed length, and varies
> [nrf noup] zephyr: Fix issues with compression TLVs

- boot/zephyr/decompression.c
Backport 16a77893d9c6c461f79178b2148159e32949d9ac from #368.
> [Backport v2.1.0-ncs2-branch] [nrf noup] zephyr: Fix issues with compression TLVs

- boot/zephyr/decompression.c
fixup! [nrf noup] zephyr: Add support for compressed image updates
Fixes an issue with using sizeof() for variables for buffer sizes instead of the actual buffer size itself
> [nrf noup] boot: zephyr: decompression: Fix stray sizeof() usage

- boot/zephyr/Kconfig
Adds selecting the experimental Kconfig when compession is in use
> [nrf noup] boot: zephyr: Add experimental selection to compression

- boot/boot_serial/src/boot_serial.c
Backport bcdf6e24493a0c3de7c5f3a126a6b4075b2ad088 from #376.
> [Backport v2.1.0-ncs2-branch] [nrf fromlist] boot_serial: Support sha256, sha384 and sha512

- boot/bootutil/src/ed25519_psa.c
Log module has been declared but never registered. This commit fixes that by just registering the module.
> [nrf noup] Fix logging for ED25519_psa

- boot/bootutil/src/ed25519_psa.c
- boot/zephyr/Kconfig
Adds a new Kconfig CONFIG_BOOT_SIGNATURE_KMU_SLOTS which allows specifying how many KMU key IDs are supported, the default is set to 1 instead of 3 which was set before
> [nrf noup] boot: bootutil: Allow configuring number of KMU keys

- boot/zephyr/Kconfig.serial_recovery
Adds additional conditions that lets the direct upload option to be selected on nRF5340 to allow for uploading network core updates directly to the network core with the flash simulator
NCSDK-30866
> [nrf noup] boot: zephyr: serial_recovery: Add nRF5340 Kconfig override

- boot/zephyr/pm.yml
Adds check to region of mcuboot_secondary_1 to put it in external flash only if CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY is set.
This should allow for DFU from internal flash on the nRF5340 with dynamic partitioning.
Also fixing a typo.
> [nrf noup] partition_manager: Add support for internal flash netcore DFU

- boot/bootutil/src/loader.c
- boot/zephyr/Kconfig
- boot/zephyr/decompression.c
nrf-squash! [nrf noup] zephyr: Add support for ARM thumb filter
Adds support to the compressed image update for allowing encrypted images. Also removes the limit of having 1 updateable image
> [nrf noup] zephyr: Add support for encrypted compressed updates

- boot/zephyr/Kconfig
- boot/zephyr/boards/nrf54h20dk_nrf54h20_cpuapp_iron.conf
- boot/zephyr/flash_map_extended.c
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- boot/zephyr/include/target.h
- boot/zephyr/nrf_cleanup.c
Added basic support for nrf54h20dk_nrf54h20_cpuapp_iron board. This PR turns off CONFIG_FPROTECT and excludes accessing hal nrf_clock.h interfaces from mcuboot for this board build.
> boot/zephyr: nrf54h20dk support

- boot/zephyr/nrf_cleanup.c
Added procedure which does configure UARTE pins to the default states. This allows to reduce power consumption if pin is floating.
Ref.: NCSIDB-1194
> boot/zephyr/nrf_cleanup: cleanup uarte pins

- boot/zephyr/Kconfig
Zephyr provides "mcuboot-mbedtls-cfg.h" as glue interface for configure mbedts. "config-tls-generic.h" default value was erroneously introduced during a meta codebase synchronization.
> [nrf noup] boot/zephyr/Kconfig: fix MBEDTLS_CFG_FILE value

- boot/zephyr/nrf_cleanup.c
Compile out code which does cleanup on UARTE pins as this cause issues on for some applications.
ref.: NCSDK-33039
> boot/zephyr/nrf_cleanup: nRF54l: disable cleanup on UARTE pins

- boot/zephyr/nrf_cleanup.c
This commit adds cleanup for GRTC and UARTE peripherals.
ref: NCSDK-32966
> [nrf noup] nrf_cleanup: nRF54h: fix missing peripheral cleanup

- boot/zephyr/main.c
pointer to the image ARM vector table should be placed out of stack which is being reconfigured before vt is used for branch to the application. This caused transient boot failure when CONFIG_LTO=y.
Moved vt to static data scope.
(cherry picked from commit 264f6ee9964d726f89da94acb55d859a6278e3c6)
> [nrf fromtree] boot/zephyr/main: fix placement of pointer to arm vector

- boot/zephyr/decompression.c
- scripts/imgtool/image.py
- scripts/imgtool/main.py
This PR aligns flash writes to any boundaries returned by
flash_area_align() instead of using a fixed 4-byte alignment.
This change ensures that the decompression code works correctly with
flash areas that may require different alignment, such as those
used by the nRF54H20 SoC.
This PR also fixes following issues:
- hash calculation of header padding with bytes other than
flash 'erased value' (may be 0x00)
- buffer overflow from previous approach of caching unaligned
ARM thumb filter output. For 'excess_data_buffer_full == true',
decomp_buf could be of DECOMP_BUF_ALLOC_SIZE size already before
moving and restoring cached data to the beginning of the buffer.
- missing ARM thumb cached bytes restoration after leaving main
decompression loop.
- in imgtool, fixes issues when trying to …
> decompression: Add nrf54h20 iron board support

- boot/bootutil/src/bootutil_misc.c
[nrf squash!] [nrf noup] boot: bootutil: Add support for NSIB maximum image size
Fixes a check which did not check that a Kconfig was set
> [nrf noup] boot: bootutil: Fix #if check

- boot/zephyr/CMakeLists.txt
- boot/zephyr/firmware_loader_bm.c
- boot/zephyr/io_bm.c
Adds firmware loader code for use in baremetal mode
> [nrf noup] boot: zephyr: Add bm firmware loader code

- boot/zephyr/Kconfig
Enable ed25519 signature as well as direct hashing while building for nRF54H20DK.
Ref: NCSDK-34304
> [nrf noup] boot: Provide default configuration for nRF54H20

- boot/bootutil/src/ed25519_psa.c
- boot/zephyr/include/nrf_cleanup.h
- boot/zephyr/main.c
Lock KMU keys before passing execution to application.
> [nrf noup] bootutil: Locking KMU keys

- boot/bootutil/src/loader.c
- boot/zephyr/main.c
nrf-squash! [nrf noup] boot: nrf53-specific customization
Fixes missing include guards for some PCD includes
> [nrf noup] boot: Fix PCD usage

- boot/zephyr/nrf_cleanup.c
Fix indexing variable mismatch.
> [nrf noup] boot/zephyr/nrf_cleanup: fix index error

- boot/zephyr/CMakeLists.txt
- boot/zephyr/io_bm.c
> [nrf noup] boot: zephyr: Fix bm IO button check

- boot/zephyr/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
Add the required zephyr,boot-partition to chosen node of the nrf54h20dk_nrf54h20_cpuapp overlay as the the board overlay overwrites the common app.overlay.
> boot: zephyr: boards: add chosen boot part nrf54h20 cpuapp overlay

- boot/zephyr/Kconfig
nrf-squash! [nrf noup] boot: zephyr: Kconfig dependencies for PSA LITE
The PSA core lite now requires the PSA_WANTs for the hashing functions to be set in order to be used so select them as normal.
> boot: zephyr: Adjust PSA requirements for PSA_CORE_LITE

- boot/zephyr/CMakeLists.txt
- boot/zephyr/main.c
- boot/zephyr/nrf_cleanup.c
This leads to stack corruption.
> [nrf noup] boot: zephyr: remove nonsecure ram cleanup

- boot/zephyr/io_bm.c
nrf-squash! [nrf noup] boot: zephyr: Add bm firmware loader code
Delays checking IO button state by 5us after pull-up has been applied to allow time for it to be applied
> [nrf noup] boot: zephyr: Delay bm IO button check

- boot/zephyr/CMakeLists.txt
- boot/zephyr/main.c
- boot/zephyr/nrf_cleanup.c
Backport 3adc1f232221dc8a6d77c378aa0d97fa24c9c0cb from #514.
> [Backport ncs-v3.1-branch] [nrf noup] boot: zephyr: remove nonsecure ram cleanup

- boot/zephyr/Kconfig
- boot/zephyr/main.c
Disables read write and execute on mcuboots NVM
at the end of execution.
> [nrf noup] boot: zephyr: Disable self RWX

- boot/bootutil/src/ed25519_psa.c
- boot/bootutil/src/image_ed25519.c
- boot/bootutil/src/image_validate.c
Thic PR introduces support for ed25519 signature verification when CONFIG_NCS_BOOT_SIGNATURE_USING_ITS is set (through PSA API).
> [nrf noup] Support for ed25519 signature verification using ITS

- boot/zephyr/CMakeLists.txt
- boot/zephyr/nrf54h20_custom_s2ram.c
- boot/zephyr/socs/nrf54h20_cpuapp.conf
Application need special support in the bootloader in order to resume the application  for suspend to RAM.
MCUboot Is just immediate actor which redirects execution to the application (application reset vector) when wake-up from S2RAM is detected. Detection is based on HW (NRF_RESETINFO) and hardened using additional check over independent source of truth (variable with magic value).
Thanks to above the application is resuming using its routines - instead of mocking that by routines compiled in by the MCUboot.
ref: NCSDK-34750
manifest-pr-skip
> [nrf noup] boot/zephyr: nRF54h20 resume from S2RAM

- boot/bootutil/src/bootutil_public.c
- boot/bootutil/src/loader.c
Fix uninitialized variable warning as well as compile time issue, when the slotted dependencies are enabled.
Upstream PR #: 2477
> [nrf fromtree] bootutil: Fix minor issues

- boot/zephyr/include/io/io.h
If a device uses RESETINFO, than there are some bits set in the resetinfo, even for reboots that should allow to interpret and enter the device recovery.
That way it is possible to recover a device through serial recovery if the main application resets due to i.e. watchdog.
Upstream PR #: 2468
> [nrf fromtree] boot: zephyr: Fix IO-based entrance method

- boot/bootutil/src/loader.c
- boot/zephyr/nrf54h20_custom_s2ram.c
Added direct-xip support to pm_s2ram nRF54h bootloader's resume implementation:
* new API for marking active slot to be used by boot_go() routines.
* jump vector assignment which is basing on above designation.
Dragged in above feature into boot_go() using API provided.
manifest-pr-skip
> [nrf noup] nRF54h20: support for S2RAM resume for DIRECT-XIP mode
