boot/zephyr/Kconfig
boot/zephyr/prj.conf
repository.yml
samples/zephyr/hello-world/CMakeLists.txt
scripts/imgtool/image.py
scripts/imgtool/main.py

[DNM] [nrf mergeup] merge upsteram up to commit aab2118 (replay)

---

boot/zephyr/boards/nrf51_pca10028.conf
boot/zephyr/boards/nrf52840_pca10059.conf
boot/zephyr/include/mcuboot_config/mcuboot_config.h

[DNM] [nrf mergeup] merge upsteram up to commit 5c877d5

---

Jenkinsfile

- remove extra args from docker plugin DSL
- fix if(PR) logic in jenkinsfile
- add downstream build of documentation with NRF/master  (this can be disabled with job parameter) 

[nrf noup] ci: add nightly cron trigger to master branch

---

Jenkinsfile

this is optional to test against nRF/master

[nrf noup] ci: turn off automatic downstream test/doc jobs

---

.github/workflows/backport.yml

Using NordicBuilder user and free-tier actions

[nrf noup] ci: Add Github-Actions:Backport-Bot

---

.gitlint
Jenkinsfile

- Add west.yml in order to get the zephyr-rtos/ci-tools. 
- update .gitlint for new ci-tools path. 
- move to CI_LIB-v2 jenkinsfile format

[nrf noup] ci: adding common cron configuration

---

boot/zephyr/pm.yml

Get rid of not-required scratch area and use move-swap instead.

Remove scratch

---

Jenkinsfile

- enable webhooks
- cron can be enabled for commit branches now. 
- better status reports
- better workspace clean

[nrf noup] ci: update jenkinsfile with new trigger/status/clean

---

boot/zephyr/pm.yml

Signed-off-by: Vidar Berg <vidar.berg@nordicsemi.no>

Clarify the purpose of the "mcuboot_pad" partition

---

.gitlint
Jenkinsfile

- replace ci-tools version of check_compliance.py
- fix west update error

[nrf noup] ci: use zephyr/scripts/ci/check_compliance.py

---

boot/zephyr/pm.yml

Introduced partition description in order to support MCUboot's direct-xip mode.

PM partitioning for the Direct Xip mode

---

boot/bootutil/src/loader.c

[nrf noup] treewide: add NCS partition manager support

---

boot/zephyr/pm.yml

fixup! [nrf noup] treewide: add NCS partition manager support
Update comment to not mention the removed SPM secure firmware solution.
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

[nrf noup] Update comment to not mention SPM

---

boot/zephyr/CMakeLists.txt

Fixes path variables to use the proper Zephyr module variables

[nrf noup] Fix path variables

---

boot/bootutil/src/loader.c

Using sequential updates on the nRF53 with external flash would cause network core updates to fail. This is because the update would be located in the external flash which is network core cannot access. This fixes the issue by copying the data from the external flash into RAM of the application core which can be read by the network core.
This commit also contains some minor renaming to align with the naming scheme used in the `loader.c` file for flash areas.
Ref: NCSDK-21379

bootutil: loader.c: Fix network core update external flash with 1 image

---

boot/bootutil/src/bootutil_misc.c
boot/bootutil/src/bootutil_public.c
boot/zephyr/include/mcuboot_config/mcuboot_config.h
boot/zephyr/include/sysflash/pm_sysflash.h
boot/zephyr/include/sysflash/sysflash.h

Add missing commits for 3 image support

---

boot/zephyr/nrf_cleanup.c

fixup! [nrf noup] zephyr: Clean up non-secure RAM if enabled
Add support for nrf54l15 UARTE20 and UARTE30.
This is reapply of the #308 (it was omitted in the last upmerge)

[nrf noup] zephyr: Clean up non-secure RAM if enabled

---

boot/zephyr/CMakeLists.txt

fixup! [nrf noup] PSA configuration required changes

[nrf noup] Exclude PSA source on non-PSA crypto configuration

---

boot/zephyr/Kconfig

fixup! [nrf noup] PSA configuration required changes

[nrf noup] Add missing selection of MBEDTLS_PSA_CRYPTO_C

---

.github/workflows/commit-tags.yml

nrf-squash! [nrf noup] github: Add a commit tags check workflow
Adapt to the changes in:
nrfconnect/action-commit-tags#4

[nrf noup] workflows: Update the commit tags action

---

.github/workflows/commit-tags.yml

nrf-squash! [nrf noup] workflows: Update the commit tags action
Fix spacing.

[nrf noup] workflows: Fix a space in the commit tags action

---

.github/workflows/backport.yml

[nrf noup] workflows: Add a backport workflow

---

boot/zephyr/decompression.c

fixup! [nrf noup] zephyr: Add support for ARM thumb filter
Fixes two issues with decompression, one with variables not being declared at the correct level and the other with the test decompression not checking the final decompressed image size
Signed-off-by: Jamie McCrae <jamie.mccrae@nordicsemi.no>
(cherry picked from commit 4fc8d2d7351b0b2e51be0c64ef5be7a521c7661f)

[nrf noup] zephyr: Fix issues with ARM thumb decompression

---

boot/zephyr/boards/nrf54l15dk_nrf54l05_cpuapp.conf
boot/zephyr/boards/nrf54l15dk_nrf54l10_cpuapp.conf

[nrf fromlist] boot: zephyr: boards: nrf54l10 and nrf54l05 configs

---

boot/bootutil/src/loader.c

[nrf noup] boot: bootutil: loader: Fix triple erasing s0/s1 update

---

boot/bootutil/include/bootutil/key_revocation.h
boot/bootutil/src/ed25519_psa.c
boot/bootutil/src/key_revocation.c
boot/bootutil/src/loader.c
boot/zephyr/CMakeLists.txt
boot/zephyr/Kconfig

Disable previous generation key when update comes with
new valid key and application is confirmed

key revocation

---

boot/zephyr/decompression.c

nrf-squash! zephyr: Add support for compressed image updates
Fixes an issue whereby compressed encrypted update images were not padded and the final part of decryption would fail due to not being a length of the block size

[nrf noup] zephyr: Fix issue with unpadded encrypted updates

---

boot/zephyr/decompression.c

Backport 3443eae6a2dd630bd9b9e3ac2c784312b69c7e2f from #420.

[Backport v2.1.0-ncs5-branch] [nrf noup] zephyr: Fix issue with unpadded encrypted updates

---

boot/zephyr/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.conf

boot: zephyr: boards: nrf54lm20apdk

---

boot/zephyr/decompression.c

This PR aligns to the changes in the nrfcompress API, which now enables the caller to provide the expected size of the decompressed image.
ref: NCSDK-32340

[nrf noup] decompression: Align to changes in nrfcompress API

---

boot/bootutil/src/ed25519_psa.c
boot/zephyr/boards/nrf54l15dk_nrf54l15_cpuapp_ext_flash.overlay
boot/zephyr/include/nrf_cleanup.h
boot/zephyr/main.c

nrf-squash! [nrf noup] boot/zephyr: add nrf54l15dk ext flash configs
Removes no longer present nodes

[nrf noup] boot: zephyr: boards: nrf54l15dk: Fix ext flash config

---

.github/workflows/manifest-PR.yml

Adding action to create manifest PRs automatically.

[nrf noup] workflows: Add manifest PRs creation

---

boot/zephyr/CMakeLists.txt
boot/zephyr/io_bm.c

[backport ncs-v3.1-branch] [nrf noup] boot: zephyr: Fix bm IO button check

---

boot/zephyr/nrf_cleanup.c

The GRTC should not reset its value and stop running when switching for
MCUBoot to application. Also in general, this should not be done in case
of reset - so the nrfx_grtc_unit function should not reset the counter
value. This will be fixed in nrfx (NRFX-8487), but the solution
is needed quicker. Hence, a temporary uninit function for GRTC was
added in nrf_cleanup, fixing this issue for MCUBoot.

[nrf noup] nrf_cleanup: temporary GRTC cleanup with no counter reset
